# Generated by Django 4.0.3 on 2022-03-20 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='place',
            new_name='visit',
        ),
    ]
